default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 11111111

development:
  <<: *default
  database: vk_development

test:
  <<: *default
  database: vk_test
