sqlite: &amp;sqlite
  adapter: sqlite3
  database: db/&lt;%= Rails.env %&gt;.sqlite3
 
mysql: &amp;mysql
  adapter: mysql2
  username: root
  password: 11111111
  database: vk_&lt;%= Rails.env %&gt;
 
postgresql: &amp;postgresql
  adapter: postgresql
  username: postgres
  password: 11111111
  database: myapp_&lt;%= Rails.env %&gt;
  min_messages: ERROR
 
defaults: &amp;defaults
  pool: 5
  timeout: 5000
  host: localhost
  &lt;&lt;: *&lt;%= ENV['DB'] || "postgresql" %&gt;
 
development:
  &lt;&lt;: *defaults
 
test:
  &lt;&lt;: *defaults
 
production:
  &lt;&lt;: *defaults
  # TODO: Add erb-echo of credentials
