default: &default
  notify_admin_about_reservations:
   cron: '0 10 * * * Ukraine/Kiev'
   class: AdminReservationsWorker
   queue: notifiers
   description: Sends email to site owner with last day reservations

development:
  <<: *default

produbtion:
  <<: *default
