contact:
  phones:
    kyivstar:
      number: 380674505505
      human_number: '+38 (067) 4-505-505'
    life:
      number: 38093­7720373
      human_number: '+38 (093) 772-03-73'
  email: 'vk.lviv.ua@gmail.com'
